require 'vsc.remap.aesthetics'
require 'vsc.remap.basics'
require 'vsc.remap.editor'
require 'vsc.remap.explorer'
require 'vsc.remap.finder'
require 'vsc.remap.git'
require 'vsc.remap.lsp'
require 'vsc.remap.panels'
require 'vsc.remap.debug'

require 'vsc.plugins'
